### ISSUE TITLE
Request: working with @use

### ISSUE THREAD

**Issue by dirkjf** [loilo/node-sass-yaml-importer#20]
Sass will phase out `@import` in favor of `@use`, see: https://sass-lang.com/documentation/at-rules/import. I am hoping this importer will also support the use of `@use`.

**Comment by dirkjf** [comment]
Actually, it appears using `@use` is already possible, as long as you use `@use .... as`.  This also allows you to omit the main index key of the file (which I think is also a plus, especially when using the file in JS files as well). Here's an example:

**colors.yaml**:

```
primary: '#2e86c1'
secondy: '#a93226'
```

**index.scss**:

```
@use 'colors.yaml' as colors;

body {
  background-color: colors.$primary;
}
```

**Comment by loilo** [comment]
The API used by this package to intercept the import is the same for `@import` and `@use`, so this importer already supports `@use`. Its usage is slightly different in that it works like all modules do: the output is namespaced by default.

**Example**

Take this `data.yml` file:
```yaml
primary: red
```

This is how it can be used with `@import`:
```scss
@import 'data.yml';

body { color: $primary; }
```

This is how it can be used with `@use`:
```scss
@use 'data.yml';

body { color: data.$primary; }
```

Of course you can apply the same techniques as you can do with any `@use` file, so you can achieve the behavior of `@import` like this:

```scss
@use 'data.yml' as *;

body { color: $primary; }
```

Thanks for pointing this out though. I was aware of this issue for a while and suspected it would just keep working, but have never verified it myself before.
